### ISSUE TITLE
Occassional segmentation fault on PHP 7.4.0

### ISSUE THREAD

**Issue by Devristo** [krakjoe/pcov#40]
First of all: Thanks a lot for this amazing project. It really saves time and headaches! 

In my brand new PCOV 1.0.6 / Symfony 4.4.0 / Behat 3.5 setup I occassionally run into a segfault that mentions pcov.  See the coredump and the backtrace below.

Unfortunately I am not able to trigger it with a small reproducer.

Is this something that can be caused by userland? Or is it perhaps a small bug in pcov or even PHP ?

```
Core was generated by `php -d extension=pcov -d pcov.enabled=1 vendor/bin/behat --profile no-bootstrap'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f554a4b4d76 in zend_mark_reachable (opcodes=0x7f554544ec00, cfg=0x7ffef075d260, b=0x7f5541250a50) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:91
91                              zend_basic_block *succ = blocks + b->successors[i];
(gdb) bt
#0  0x00007f554a4b4d76 in zend_mark_reachable (opcodes=0x7f554544ec00, cfg=0x7ffef075d260, b=0x7f5541250a50) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:91
#1  0x00007f554a4b4f91 in zend_mark_reachable (opcodes=0x7f554544ec00, cfg=0x7ffef075d260, b=0x7f5541053650) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:148
#2  0x00007f554a4b4f91 in zend_mark_reachable (opcodes=0x7f554544ec00, cfg=0x7ffef075d260, b=0x7f55410535d0) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:148
#3  0x00007f554a4b4f91 in zend_mark_reachable (opcodes=0x7f554544ec00, cfg=0x7ffef075d260, b=0x7f5541053510) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:148
#4  0x00007f554a4b5010 in zend_mark_reachable_blocks (op_array=0x7f5544579690, cfg=0x7ffef075d260, start=0) at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:161
#5  0x00007f554a4b71a3 in zend_build_cfg (arena=0x7ffef075d2e8, op_array=0x7f5544579690, build_flags=2147483648, cfg=0x7ffef075d260)
    at /tmp/pear/temp/pcov/cfg/703/zend_cfg.c:639
#6  0x00007f554a4b3abd in php_pcov_discover_code (arena=0x7ffef075d2e8, ops=0x7f5544579690, return_value=0x7ffef075d2f0) at /tmp/pear/temp/pcov/pcov.c:544
#7  0x00007f554a4b3ecf in php_pcov_discover_file (file=0x7f55447bb180, return_value=0x7f554a8175c0) at /tmp/pear/temp/pcov/pcov.c:624
#8  0x00007f554a4b4259 in php_pcov_collect (execute_data=0x7f554a8175f0, return_value=0x7f554a8175c0) at /tmp/pear/temp/pcov/pcov.c:691
#9  0x000055f0882a57fc in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1525
#10 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a817510) at /usr/src/php/Zend/zend_vm_execute.h:61485
#11 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a817510) at /tmp/pear/temp/pcov/pcov.c:252
#12 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a817510) at /tmp/pear/temp/pcov/pcov.c:291
#13 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#14 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8173e0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#15 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8173e0) at /tmp/pear/temp/pcov/pcov.c:252
#16 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8173e0) at /tmp/pear/temp/pcov/pcov.c:291
#17 0x000055f0882a5b39 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1601
#18 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a817350) at /usr/src/php/Zend/zend_vm_execute.h:61485
#19 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a817350) at /tmp/pear/temp/pcov/pcov.c:252
#20 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a817350) at /tmp/pear/temp/pcov/pcov.c:291
#21 0x000055f088219184 in zend_call_function (fci=0x7ffef075d960, fci_cache=0x7ffef075d940) at /usr/src/php/Zend/zend_execute_API.c:811
#22 0x000055f0880439a0 in zif_call_user_func_array (execute_data=0x7f554a8172e0, return_value=0x7f554a817270) at /usr/src/php/ext/standard/basic_functions.c:4960
#23 0x000055f0882a60a5 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1729
#24 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a817140) at /usr/src/php/Zend/zend_vm_execute.h:61485
#25 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a817140) at /tmp/pear/temp/pcov/pcov.c:252
#26 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a817140) at /tmp/pear/temp/pcov/pcov.c:291
#27 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#28 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a817090) at /usr/src/php/Zend/zend_vm_execute.h:61485
#29 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a817090) at /tmp/pear/temp/pcov/pcov.c:252
#30 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a817090) at /tmp/pear/temp/pcov/pcov.c:291
#31 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#32 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816f80) at /usr/src/php/Zend/zend_vm_execute.h:61485
#33 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816f80) at /tmp/pear/temp/pcov/pcov.c:252
#34 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816f80) at /tmp/pear/temp/pcov/pcov.c:291
#35 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#36 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816db0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#37 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816db0) at /tmp/pear/temp/pcov/pcov.c:252
#38 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816db0) at /tmp/pear/temp/pcov/pcov.c:291
#39 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#40 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816d00) at /usr/src/php/Zend/zend_vm_execute.h:61485
#41 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816d00) at /tmp/pear/temp/pcov/pcov.c:252
#42 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816d00) at /tmp/pear/temp/pcov/pcov.c:291
#43 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#44 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816c00) at /usr/src/php/Zend/zend_vm_execute.h:61485
#45 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816c00) at /tmp/pear/temp/pcov/pcov.c:252
#46 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816c00) at /tmp/pear/temp/pcov/pcov.c:291
#47 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#48 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816a80) at /usr/src/php/Zend/zend_vm_execute.h:61485
#49 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816a80) at /tmp/pear/temp/pcov/pcov.c:252
#50 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816a80) at /tmp/pear/temp/pcov/pcov.c:291
#51 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#52 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8168d0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#53 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8168d0) at /tmp/pear/temp/pcov/pcov.c:252
#54 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8168d0) at /tmp/pear/temp/pcov/pcov.c:291
#55 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#56 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816690) at /usr/src/php/Zend/zend_vm_execute.h:61485
#57 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816690) at /tmp/pear/temp/pcov/pcov.c:252
#58 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816690) at /tmp/pear/temp/pcov/pcov.c:291
#59 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#60 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8163f0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#61 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8163f0) at /tmp/pear/temp/pcov/pcov.c:252
#62 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8163f0) at /tmp/pear/temp/pcov/pcov.c:291
#63 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#64 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816350) at /usr/src/php/Zend/zend_vm_execute.h:61485
#65 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816350) at /tmp/pear/temp/pcov/pcov.c:252
#66 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816350) at /tmp/pear/temp/pcov/pcov.c:291
#67 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#68 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8162b0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#69 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8162b0) at /tmp/pear/temp/pcov/pcov.c:252
#70 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8162b0) at /tmp/pear/temp/pcov/pcov.c:291
#71 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#72 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a816050) at /usr/src/php/Zend/zend_vm_execute.h:61485
#73 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a816050) at /tmp/pear/temp/pcov/pcov.c:252
#74 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a816050) at /tmp/pear/temp/pcov/pcov.c:291
#75 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#76 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815fb0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#77 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815fb0) at /tmp/pear/temp/pcov/pcov.c:252
--Type <RET> for more, q to quit, c to continue without paging--c
#78 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815fb0) at /tmp/pear/temp/pcov/pcov.c:291
#79 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#80 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815f10) at /usr/src/php/Zend/zend_vm_execute.h:61485
#81 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815f10) at /tmp/pear/temp/pcov/pcov.c:252
#82 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815f10) at /tmp/pear/temp/pcov/pcov.c:291
#83 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#84 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815c60) at /usr/src/php/Zend/zend_vm_execute.h:61485
#85 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815c60) at /tmp/pear/temp/pcov/pcov.c:252
#86 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815c60) at /tmp/pear/temp/pcov/pcov.c:291
#87 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#88 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815bd0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#89 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815bd0) at /tmp/pear/temp/pcov/pcov.c:252
#90 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815bd0) at /tmp/pear/temp/pcov/pcov.c:291
#91 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#92 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815b30) at /usr/src/php/Zend/zend_vm_execute.h:61485
#93 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815b30) at /tmp/pear/temp/pcov/pcov.c:252
#94 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815b30) at /tmp/pear/temp/pcov/pcov.c:291
#95 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#96 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815910) at /usr/src/php/Zend/zend_vm_execute.h:61485
#97 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815910) at /tmp/pear/temp/pcov/pcov.c:252
#98 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815910) at /tmp/pear/temp/pcov/pcov.c:291
#99 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#100 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815780) at /usr/src/php/Zend/zend_vm_execute.h:61485
#101 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815780) at /tmp/pear/temp/pcov/pcov.c:252
#102 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815780) at /tmp/pear/temp/pcov/pcov.c:291
#103 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#104 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815640) at /usr/src/php/Zend/zend_vm_execute.h:61485
#105 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815640) at /tmp/pear/temp/pcov/pcov.c:252
#106 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815640) at /tmp/pear/temp/pcov/pcov.c:291
#107 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#108 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a815260) at /usr/src/php/Zend/zend_vm_execute.h:61485
#109 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a815260) at /tmp/pear/temp/pcov/pcov.c:252
#110 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a815260) at /tmp/pear/temp/pcov/pcov.c:291
#111 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#112 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a814f00) at /usr/src/php/Zend/zend_vm_execute.h:61485
#113 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a814f00) at /tmp/pear/temp/pcov/pcov.c:252
#114 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a814f00) at /tmp/pear/temp/pcov/pcov.c:291
#115 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#116 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8148e0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#117 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8148e0) at /tmp/pear/temp/pcov/pcov.c:252
#118 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8148e0) at /tmp/pear/temp/pcov/pcov.c:291
#119 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#120 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8146c0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#121 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8146c0) at /tmp/pear/temp/pcov/pcov.c:252
#122 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8146c0) at /tmp/pear/temp/pcov/pcov.c:291
#123 0x000055f0882a5fea in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1713
#124 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a8141e0) at /usr/src/php/Zend/zend_vm_execute.h:61485
#125 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a8141e0) at /tmp/pear/temp/pcov/pcov.c:252
#126 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a8141e0) at /tmp/pear/temp/pcov/pcov.c:291
#127 0x000055f0882a5b39 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/php/Zend/zend_vm_execute.h:1601
#128 0x000055f08830e917 in zend_vm_call_opcode_handler (ex=0x7f554a814020) at /usr/src/php/Zend/zend_vm_execute.h:61485
#129 0x00007f554a4b2f32 in php_pcov_trace (execute_data=0x7f554a814020) at /tmp/pear/temp/pcov/pcov.c:252
#130 0x00007f554a4b3065 in php_pcov_execute_ex (execute_data=0x7f554a814020) at /tmp/pear/temp/pcov/pcov.c:291
#131 0x000055f08830d9e5 in zend_execute (op_array=0x7f554a88c300, return_value=0x0) at /usr/src/php/Zend/zend_vm_execute.h:57651
#132 0x000055f088232435 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/php/Zend/zend.c:1663
#133 0x000055f088192377 in php_execute_script (primary_file=0x7ffef0761920) at /usr/src/php/main/main.c:2619
#134 0x000055f0883105be in do_cli (argc=10, argv=0x55f08919f030) at /usr/src/php/sapi/cli/php_cli.c:961
#135 0x000055f088311728 in main (argc=10, argv=0x55f08919f030) at /usr/src/php/sapi/cli/php_cli.c:1352
```

**Comment by krakjoe** [comment]
The trace terminates deep within code that is copied from opcache, so that's pretty strange behaviour.

I'm afraid I can't investigate without a reproducing test case.

**Comment by Devristo** [comment]
I was afraid of that. So far I am unsuccessful in creating a small reproducer. But will give it another go and will let you know.

**Comment by krakjoe** [comment]
Reading the thread on the symfony issue leads me to conclude that this is a bug in PHP, not pcov.

**Comment by Devristo** [comment]
:+1:  I tend to agree, since I haven't seen the segfault after some patches by the Symfony team.
